### ISSUE TITLE
No input sources found on AVR

### ISSUE THREAD

**Issue by 2t0m** [crowbarz/ha-pioneer_async#1]
Hi @crowbarz and thanks for this great idea of maintaining a single continuous telnet session to AVR.

I would like to use your component with my VSX-S510 but I have a Runtime Error: No input sources found on AVR.

`Error setting up entry 192.168.1.123:8102 for pioneer_async
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 222, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/config/custom_components/pioneer_async/__init__.py", line 73, in async_setup_entry
    await pioneer.build_source_dict()
  File "/config/custom_components/pioneer_async/pioneer_avr.py", line 533, in build_source_dict
    raise RuntimeError("No input sources found on AVR")
RuntimeError: No input sources found on AVR`

Can I manually add input sources ?

Thanks

**Comment by 2t0m** [comment]
I did with
```
self._source_name_to_id = {"TV":"06","GCast":"15"}
self._source_id_to_name = {"06":"TV","15":"GCast"}
```
I can now try you component !

**Comment by crowbarz** [comment]
Hi @2t0m, I guess your VSX model is not responding to the `?RGBxx` command that the integration sends to poll the input names. I wondered if all VSX models supported that functionality and it would seem that they don't.

I (re-)added a `source` option in 41d2247c0c7a89574a00c91e27f040656f7076a5 to manually specify sources when configured via `configuration.yaml`. It will now only poll the AVR for sources if they are not manually specified. Does this make the integration work for you without hacking the sources into the code?

I'm not sure how to get a dictionary from the user via config flow, so this is unimplemented via the UI for now.

**Comment by 2t0m** [comment]
Yes, it does work with :

```
media_player:
  - platform: pioneer_async
    host: 192.168.1.123
    sources: { TV: '06', GCast: '15' }
```
Thanks !

NB : The connection is much more stable with a single continuous telnet session.
