### ISSUE TITLE
Invalid literal for int()

### ISSUE THREAD

**Issue by MahrWe** [crowbarz/ha-pioneer_async#13]
Since the update to the release 0.7.0 i am receiving the following errors from this integration:

```Logger: aiopioneer.pioneer_avr
Source: runner.py:128
First occurred: 27. Februar 2023 um 01:20:56 (53 occurrences)
Last logged: 28. Februar 2023 um 22:59:24

>> PioneerAVR._connection_listener() exception: invalid literal for int() with base 10: ''
>> PioneerAVR._connection_listener() exception: string index out of range
```

Despite these errors I did not find any problems with controlling my AVR.

I have installed the integration via HACS and configured my AVR in yaml, to increase the timeout (needed it for the previous release).

**Comment by spudje** [comment]
I have the same errors.

**Comment by MahrWe** [comment]
I have enabled logging as per instruction. I have reduced the log to only include lines referring to "pioneer". 
The contents of the log don´t tell me much, I could just find the error will occure between sending ?VST to the AVR and receiving the response.
I hope this can help.
[home-assistant_pioneer.log](https://github.com/crowbarz/ha-pioneer_async/files/10865479/home-assistant_pioneer.log)

**Comment by MahrWe** [comment]
The Reciever states the following firmware id: 1-151-081-111-031 
I have the model VSX-921 (I think with "-k" suffix?).
I did manually update the firmware via USB at some point because of network issues I had. This was way after official update-servers were shutdown, I guess. The firmware file is named: AVR_12_0236.mem

**Comment by 11harveyj** [comment]
I can't find any docs on the AVRs serial interface so not sure on the decoding of responses for VST and AST commands for AVRs manufactured <=2012. I've sent an email off to Pioneer in hopes they might be able to provide some docs, but I'm quite doubtful.

The immediate "workaround" to get rid of the errors is to disable the extended audio/video functionality for VSX-921 range of amplifiers. I don't think any of the new stuff has been exposed in HA yet anyway so this won't impact the functionality you currently have.

**Comment by 11harveyj** [comment]
> I have the same errors.

@spudje do you have the same model of AVR?

**Comment by MahrWe** [comment]
> I can't find any docs on the AVRs serial interface so not sure on the decoding of responses for VST and AST commands for AVRs manufactured <=2012. I've sent an email off to Pioneer in hopes they might be able to provide some docs, but I'm quite doubtful.
> 
> The immediate "workaround" to get rid of the errors is to disable the extended audio/video functionality for VSX-921 range of amplifiers. I don't think any of the new stuff has been exposed in HA yet anyway so this won't impact the functionality you currently have.

Apparently my model is very similar to the later model version 1021k. They share the same hardware manual, and I think even firmware. Not sure if it helps maybe there is more docs for 1021k.

**Comment by 11harveyj** [comment]
The closest I've got is the VSX-***2 models (such as VSX-922 or VSX-1022), which all say that the responses for the VST/AST commands are all 40 odd data bits long (with a number "reserved for future use"), whereas your AVR seems to only be returning around 20 data bits.

Thank you for confirming though, I've started some work to at least disable that functionality for now by default (although it can be overridden with the config parameters).

**Comment by D-Jeffrey** [comment]
> I can't find any docs on the AVRs serial interface so not sure on the decoding of responses for VST and AST commands for AVRs manufactured <=2012. I've sent an email off to Pioneer in hopes they might be able to provide some docs, but I'm quite doubtful.
> 
> The immediate "workaround" to get rid of the errors is to disable the extended audio/video functionality for VSX-921 range of amplifiers. I don't think any of the new stuff has been exposed in HA yet anyway so this won't impact the functionality you currently have.

`?AST<CR>`	Request AUDIO information	`AST*<CR+LF>`	        See "command list2" sheet.
`?VST<CR>`	Request VIDEO information	`VST*<CR+LF>`		See "command list2" sheet.

[Command list 2](https://github.com/D-Jeffrey/pioneer_vsx/blob/master/FY16AVR_External_Command_for_CI_2-Command_list2.pdf)

**Comment by 11harveyj** [comment]
> > I can't find any docs on the AVRs serial interface so not sure on the decoding of responses for VST and AST commands for AVRs manufactured <=2012. I've sent an email off to Pioneer in hopes they might be able to provide some docs, but I'm quite doubtful.
> > The immediate "workaround" to get rid of the errors is to disable the extended audio/video functionality for VSX-921 range of amplifiers. I don't think any of the new stuff has been exposed in HA yet anyway so this won't impact the functionality you currently have.
> 
> `?AST<CR>` Request AUDIO information `AST*<CR+LF>` See "command list2" sheet. `?VST<CR>` Request VIDEO information `VST*<CR+LF>` See "command list2" sheet.
> 
> Data to 53 digits [2014 Command list 2](https://github.com/D-Jeffrey/pioneer_vsx/blob/master/FY16AVR_External_Command_for_CI_2-Command_list2.pdf)
> 
> Older version is data to 43 digits [2011 Command List 2](https://github.com/D-Jeffrey/pioneer_vsx/blob/master/2011_Pioneer_AVR_IP_%26_RS-232_USA%20Models_8.6-CommandList2.pdf)

Thanks, thing is this is still incorrect for the vsx-921 as it doesn't return that many digits at all (around half)

**Comment by D-Jeffrey** [comment]
I have the same error except it is on both `?VST` and `?AST`.  I have a VSX-925 (which does not response to the `?RGD`)

[home-assistant_2023-03-04T16-23-00.255Z.log](https://github.com/crowbarz/ha-pioneer_async/files/10889138/home-assistant_2023-03-04T16-23-00.255Z.log)

I think if there was a 
     `if len(value) > 43:`
at line 2420 for the remainder of the block and 
     `if len(value) > 33:`
at line 2573

It might fix it up.

Two questions:
1. how do I use the CLI for aiopioneer from within HA to try and test some things out and 
2. where is the code for aiopioneer stored, because I can not find it to try editing it (or updating).

**Comment by 11harveyj** [comment]
> I have the same error except it is on both `?VST` and `?AST`. I have a VSX-925 (which does not response to the `?RGD`)
> 
> [home-assistant_2023-03-04T16-23-00.255Z.log](https://github.com/crowbarz/ha-pioneer_async/files/10889138/home-assistant_2023-03-04T16-23-00.255Z.log)
> 
> I think if there was a `if len(value) > 43:` at line 2420 for the remainder of the block and `if len(value) > 33:` at line 2573
> 
> It might fix it up.
> 

I'll checkout the VSX-925, are you able to provide some logs so I can see a sample response for?

> 1. how do I use the CLI for aiopioneer from within HA to try and test some things out and

Not sure you can use the CLI directly from HA, as long as python3 is installed on a machine (Windows, Mac, Linux) you should be able to clone the repo to your machine and run the CLI directly (see the info here for more: )

> 2. where is the code for aiopioneer stored, because I can not find it to try editing it (or updating).

Do you mean on HA? If so it installs automatically when you create the integration, another one I'm not sure on, but I've actually forked the repo, and then updated the manifest.json for the custom integration to point directly to the git repository instead.

**Comment by 11harveyj** [comment]
@D-Jeffrey can you test this on your AVR?

https://github.com/crowbarz/aiopioneer/pull/7

The parameters seem to actually all be the same as newer AVRs which is good.

**Comment by D-Jeffrey** [comment]
@MahrWe This should be fixed with 0.7.2

**Comment by spudje** [comment]
Sorry for the late reply, I have a VSX-922.

**Comment by MahrWe** [comment]
I did the update today. Everything seems do work fine and I had no error-messages since the update.
