### ISSUE TITLE
Global AVR parameters not shown on zone 1

### ISSUE THREAD

**Issue by pantherale0** [crowbarz/ha-pioneer_async#24]
After we refactored the parser in the latest update, a number of responses no longer have an associated zone which stops HA from picking up a large number of global attributes unless a zone specific attribute is updated (such as volume).

Raising this issue more as a note. @crowbarz I'm tempted to just add a check into `_parse_response` for aiopioneer and add zone 1 to `updated_zones` if the parser response zone was null. What do you think?

**Comment by crowbarz** [comment]
I was thinking yesterday that there is a need for `Zones.All` or `Zones.None` to cover commands for attributes that are independent of zones. That could also be used in the parser table and trigger an update in the HA component for wherever it decides these attributes should go. In the interim maybe we can add `None` to  updated_zones and have the HA integration decide what to update. (I haven't looked at the code to see how `updated_zones` is processed.

**Comment by 11harveyj** [comment]
I think a `Zones.All` would be good, I'll do some work in aiopioneer to add that in.

**Comment by crowbarz** [comment]
In #35 I've added HA `DataCoordinator`s for each zone to trigger zone entity refreshes via a callback from aiopioneer. The HA `media_player` entity attaches to that, as do the new zone related property entities (sensors, binary_sensors, etc.) There's also now a `DataCoordinator` for `Zones.ALL` that global entities attach to, which triggers a refresh when any global properties are updated. This works for global attribute groups such as the tuner, audio parameters and video parameters, so I think the original issue will be resolved on the next release.

Interestingly, HA attributes that have `dict` values (eg. the `audio` and `video` attributes that were formerly on the `media_player` entity) don't seem to be refreshed properly on the `Developer Tools > States` UI, so perhaps that isn't a great way to expose structured data.

**Comment by crowbarz** [comment]
This is resolved with the [0.9.0 release](https://github.com/crowbarz/ha-pioneer_async/releases/tag/0.9.0)
