### ISSUE TITLE
VSX 828 not working

### ISSUE THREAD

**Issue by StefanW86** [crowbarz/ha-pioneer_async#27]
Hi,
i have a VSX 828 and its not working. I start the configuration, after some time it stops with the following error
`Logger: homeassistant.config_entries
Source: custom_components/pioneer_async/__init__.py:160
Integration: Pioneer AVR ([documentation](https://github.com/crowbarz/ha-pioneer_async))
First occurred: 13:36:19 (1 occurrences)
Last logged: 13:36:19

Error setting up entry 192.168.178.30:8102 for pioneer_async
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/pioneer_async/__init__.py", line 160, in async_setup_entry
    await pioneer.build_source_dict()
  File "/usr/local/lib/python3.10/site-packages/aiopioneer/pioneer_avr.py", line 766, in build_source_dict
    response = await self.send_raw_request(
  File "/usr/local/lib/python3.10/site-packages/aiopioneer/pioneer_avr.py", line 608, in send_raw_request
    response = await self._read_response(timeout=self._timeout)
  File "/usr/local/lib/python3.10/site-packages/aiopioneer/pioneer_avr.py", line 530, in _read_response
    done, pending = await asyncio.wait(  # pylint: disable=unused-variable
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 384, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 491, in _wait
    await waiter
asyncio.exceptions.CancelledError`

Can you try to fix it?

connecting via telnet to Port 8102 is working. Changing source and do other things are also workig. the avr is running at the moment of initialisation.

**Comment by crowbarz** [comment]
I am rethinking that part of the code to attempt to avoid a few race conditions that you might be hitting.

It appears to be failing when building the source dictionary, but this only happens on integration start and also when you reconfigure the integration via the UI. How long do you mean when you say that it stops "after some time" - ~seconds, ~minutes or ~hours?

**Comment by crowbarz** [comment]
Adding the integration via the UI currently doesn't allow you to specify sources manually and always polls them from the AVR, at least initially. However, I am aware that some AVRs don't support this functionality.

In the next release, you will be able to disable the initial automatic source query when configured via the UI and specify your own set of sources manually, and for those AVRs supporting automatic source queries you'll be able to edit the discovered sources. That should hopefully allow AVRs such as yours to be configured through the UI as well.

**Comment by crowbarz** [comment]
Please try 0.8.4 and see if this solves your problem. When configured via the UI, you should now be able to configure sources manually by unchecking Query AVR Sources on the first configuration page, submitting the form, then adding sources manually on the next page.

**Comment by crowbarz** [comment]
No response for >6 months so assuming fixed.
