### ISSUE TITLE
Stuck on "Please wait, starting configuration wizard for pioneer_async"

### ISSUE THREAD

**Issue by das-korn** [crowbarz/ha-pioneer_async#30]
Hi,

i installed the integration via HACS (v0.8.4) and then tried to add the integration in Settings->Devices & Services. Unfortunately the process get stuck on "Please wait, starting configuration wizard for pioneer_async".

Kind regards

**Comment by pantherale0** [comment]
Hi,

Can you provide some logs please?

Thanks
