### ISSUE TITLE
Integration not working anymore

### ISSUE THREAD

**Issue by StefanW86** [crowbarz/ha-pioneer_async#31]
Hi,

my integration works well the last months. But after some days the status not changed. today i rebooted my home assistant. If if take a look under integration, i see that the entity will not be provided by pioneer_async anymore.
Home assistant is the actual version 2023.8.4.

i configured it manually through config file like this.

`media_player:
  - platform: pioneer_async
    name: Pioneer AVR
    host: 192.168.178.30
    port: 8102
    scan_interval: 60
    timeout: 5.0
    sources: { TV: '05', SAT: '06', GAME: '49' }`

**Comment by pantherale0** [comment]
Try increasing the timeout, although looking at this you should be able to configure this from inside HA under "devices & services" without the need to use the configuration file.

Are there any errors in the logs?

**Comment by StefanW86** [comment]
sorry, it seems that the problem is the av receiver self. It is actually not reachable from the network.

**Comment by StefanW86** [comment]
can be closed

**Comment by StefanW86** [comment]
can be closed
