### ISSUE TITLE
Not working with HA 2024.1.0

### ISSUE THREAD

**Issue by pipip** [crowbarz/ha-pioneer_async#32]
Integration does notwork anymore with Home Assistant 2024.01. For me it does not connect to the receiver anymore. There seems to be changes for media_player with the HA release. Many others like mopidy have also issues with the new release, e.g.:
`state method in media_player changed from property to cached_property`

Receiver is reachable via browser but integration says it cannot connect:
`Cannot connect to AVR: [Errno 111] Connect call failed`

**Comment by pantherale0** [comment]
Not something I've experienced here on 2024.1.0.

Could you upload full debug logs?

**Comment by pipip** [comment]
@pantherale0: You are right, sorry.
For some reason I had to change the port. Port 23 always worked for me and is also displayed in the pioneer webinterface. Port 8102 works.

**Comment by pantherale0** [comment]
Yeah, 8102 is usually a safe bet. Its also worth noting that Pioneer AVR's sometimes become unresponsive entirely (something I've mentioned around here a few times). So always try a full power down by unplugging the power cable and plug back in after 30 seconds or so..

Admittedly I've not had to go that far for a good few months now though. Glad its sorted for you.
