### ISSUE TITLE
VSX-LX505 doesn't work

### ISSUE THREAD

**Issue by koboldmakiPIT** [crowbarz/ha-pioneer_async#34]
Hallo,

I hope you can help me. I am a "normal" user in HA.
I have add the HACS ha-pioneer_async integration and die install wizard starts

I add the ip-adress and test some ports 8102, 23 and try some other ports there are open on the pioneer. 
But I can´t integrate the receiver VSX-LX505. 

I got this Error Message:
Cannot connect to AVR: [Errno 111] Connect call failed ('192.168.xxx.xxx', 8102)

2024-03-29 20:24:45.430 ERROR (MainThread) [custom_components.pioneer_async.config_flow] unexpected exception: AVR connection not available
2024-03-29 20:28:06.771 ERROR (MainThread) [aiopioneer.pioneer_avr] cannot execute system_query_mac_addr command: AVR connection not available
2024-03-29 20:28:06.772 ERROR (MainThread) [aiopioneer.pioneer_avr] cannot execute system_query_software_version command: AVR connection not available
2024-03-29 20:28:06.774 ERROR (MainThread) [custom_components.pioneer_async.config_flow] unexpected exception: AVR connection not available

Have someone a idee?
Where I can get more Logs?

**Comment by crowbarz** [comment]
This integration is unlikely to support your model of Pioneer AVR. The manual that I found online for your model of AVR is dated 2021, so it probably uses a newer protocol than the one implemented in this integration. You can try the Onkyo integration - the same company owns the Pioneer, Onkyo and Integra brands now, and apparently hardware is shared across all of the brands.

There is more discussion on AVR models that work with this integration here: https://github.com/crowbarz/ha-pioneer_async/issues/20

**Comment by koboldmakiPIT** [comment]
Hello, I have tried some Onkyo and Integra integration build-in HA and from HACS/Github.
 
Unfortunately no integration work. 
Is there anybody with other ideas?

Is it possible to use RS232 AV control interface?

Here are websites with information:
https://www.reddit.com/r/homeautomation/comments/5olz46/home_assistant_and_rs232_av_control/
https://www.pioneerelectronics.com/StaticFiles/PUSA/Files/Home%20Custom%20Install/VSX-23TXH-RS232.pdf
https://github.com/Priyantha/nl.priyantha.pioneer-vsx-rs232

**Comment by pantherale0** [comment]
> Is it possible to use RS232 AV control interface?

If it has an RS232 port, you should be able to use a ser2net bridge to use this integration (or similar such as https://github.com/yuri-rage/ESP-Serial-Bridge). Quick glance, the protocol itself appears to be identical to what has been built.

The initial error you've got though appears to say that what ever service is running on the ports you have tried, isn't responding on IP you have. Check the settings of the AVR to confirm its IP address and port numbers.

**Comment by D-Jeffrey** [comment]
That is a feature rich unit you got there.  I think you should check the native services of HA:

- DLNA Digital Media Renderer (Windows Media Player reference in the manual)
- Sonos
- Alexa Media Player
- Amazon Alexa
- Google Cast
- web port looks to be 80 (admin/admin) maybe https (but unlikely)

If it is a Onkyo then you should see a when telneting to port 42424 , if that is the place then you would try https://github.com/miracle2k/onkyo-eiscp as [crowbarz](https://github.com/crowbarz) mentioned from that discussion.
