### ISSUE TITLE
0.8.6 stopped working, unable to update to 0.9.0

### ISSUE THREAD

**Issue by lennie-BE** [crowbarz/ha-pioneer_async#40]
Version 0.8.6 stopped working completely unexpectedly today. Couldn't get it to work anymore.
Checked HACS and found out there was an update. But installation keeps goiing on forever...
Probably the error is somewhere on my site, but can't find out what it is.
No remaining references in configuration.yaml, removed them month's ago.

UPDATE: got a little further. Finally it installed. After reboot I could add the integration. But after filling out the detail in te configuration panel I get this error: 
Pioneer AVR
Translation Error: The intl string context variable "exception" was not provided to the string "Unexpected exception: {exception}"

Any suggestions?

**Comment by crowbarz** [comment]
Ok, that helps pinpoint the issue a little more.

In your HA profile, do you have the language set to something other than `English` or one of its variants? If so then what is the error message when the language is set to `English`?

**Comment by lennie-BE** [comment]
I presume you mean the Language setting under Settings -> System -> General?

It was set to Dutch. I changed it to English, but the whole interface stays in Dutch, even after a reboot.

And the error with the integration stays the same.

**Comment by crowbarz** [comment]
I think the language setting that you mentioned is the system-wide language setting that is inherited for new users, but I'm not sure if changing that changes the language for existing users.

You can update the per-profile language setting in the left sidebar: (Profile Name - bottom icon) > General > User Settings > Language.

**Comment by lennie-BE** [comment]
You're absolutely right. Changed the language there from Dutch to English and that indeed changes the whole interface to English, unfortunatly the error message when trying to add the integrations stays exactly the same.

**Comment by crowbarz** [comment]
Can you navigate to Settings > System > Logs and search for `pioneer_async` and `aiopioneer`?

It will be impossible to understand what is happening on your system without knowing exactly what exception has been encountered here.

**Comment by lennie-BE** [comment]
Some errors pop up. The most important seems this one to me:
`This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:986
integration: HACS (documentation, issues)
First occurred: 9:31:26 PM (4 occurrences)
Last logged: 9:31:26 PM

<Integration crowbarz/ha-pioneer_async> [number.py] was not downloaded.
<Integration crowbarz/ha-pioneer_async> [__init__.py] was not downloaded.
<Integration crowbarz/ha-pioneer_async> [const.py] was not downloaded.
<Integration crowbarz/ha-pioneer_async> [binary_sensor.py] was not downloaded.`

Seems indeed like there is something going on with the downloads.

**Comment by lennie-BE** [comment]
This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:734
integration: HACS (documentation, issues)
First occurred: 8:43:06 PM (65 occurrences)
Last logged: 9:31:24 PM

A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/crowbarz/ha-pioneer_async/0.9.0/custom_components/pioneer_async/const.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 1
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/crowbarz/ha-pioneer_async/0.9.0/custom_components/pioneer_async/number.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/crowbarz/ha-pioneer_async/0.9.0/custom_components/pioneer_async/__init__.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/crowbarz/ha-pioneer_async/0.9.0/custom_components/pioneer_async/const.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/crowbarz/ha-pioneer_async/0.9.0/custom_components/pioneer_async/binary_sensor.py, using over 60 seconds to download a single file is not normal. This is not a problem with HACS but how your host communicates with GitHub. Retrying up to 5 times to mask/hide your host/network problems to stop the flow of issues opened about it. Tries left 0

**Comment by crowbarz** [comment]
That looks like HACS has not downloaded the integration properly as there is an issue with communicating with GitHub. My guess is that HACS does not have a GitHub authorisation and so its requests are being rate limited to 60 requests an hour, as described [here](https://hacs.xyz/docs/faq/github_account/), but that is just a guess because I don't know how HACS works under the hood.

I would suggest removing and reinstalling HACS, re-authorising access to GitHub as part of the install procedure, then reinstalling this integration.

**Comment by crowbarz** [comment]
BTW I found the issue causing the error message, and that will be fixed in the next release. However it is not really going to help here as most of the integration's files were not downloaded.

**Comment by lennie-BE** [comment]
<img width="937" alt="Schermafbeelding 2024-06-05 om 22 33 34" src="https://github.com/crowbarz/ha-pioneer_async/assets/92228335/d2bbb2b6-855c-40df-b158-09fecbb4d3a7">
Seems complete to me now. That's a screenshot if I check the pioneer_async folder via SMB. I deleted all remains of it before, again, trying to install.
But unfortunatly I keep getting the same error.

**Comment by lennie-BE** [comment]
<img width="1174" alt="Schermafbeelding 2024-06-05 om 22 40 00" src="https://github.com/crowbarz/ha-pioneer_async/assets/92228335/e6427261-701d-401c-a343-4b3d1b1fa576">
Now I get these errors in the logs. The download errors disappeared.

**Comment by crowbarz** [comment]
That error appears if the integration can't detect the main zone on your AVR. Try enabling `Don't check volume when querying AVR source` on the initial screen.

What is the model for your AVR?

**Comment by lennie-BE** [comment]
I probably found the reason for the timeouts to Github. According to https://github.com/hacs/integration/issues/3522 it's related to using IPv6. I actually enabled IPv6 on my network last week. I disabled it again now. Updates via HACS (a had some other custom integrations to update) seem to go much faster again.

Unfortunatly none of the 3 settings for "Don't check volume when querying AVR source" seems to make a difference.

My AVR is a VSX-922. Worked perfectly in combination with HA for 2 years now.

**Comment by crowbarz** [comment]
What happens if you add the integration whilst the AVR in?

It would be useful if you could obtain the debug log for the integration setup by enabling debug logging. You can normally do this from the integration page, but that page is not accessible until you add the integration. So in this case you will need to add entries in `configuration.yaml` to the `logger` integration to set the logging level for `custom_components.pioneer_async` and `aiopioneer` to `debug` as outlined in [Logger](https://www.home-assistant.io/integrations/logger/), and then restart HA before trying to add the integration again.

**Comment by lennie-BE** [comment]
I don't really understand what you mean by "What happens if you add the integration whilst the AVR in?".

Will try to set up the logging. But, I'm sorry, that will have to wait. It's getting late, and I have to get up early tomorrow.

**Comment by crowbarz** [comment]
Sorry, phone autocorrect - I meant if the AVR is turned on when adding the integration
