### ISSUE TITLE
Add capability to send arbitrary command to Pioneer AVR

### ISSUE THREAD

**Issue by crowbarz** [crowbarz/ha-pioneer_async#41]
Expose `aiopioneer.send_command` and possibly `aiopioneer.send_raw_command` as services so that commands not yet implemented can be used. Follow-up from crowbarz/aiopioneer#33.

**Comment by crowbarz** [comment]
This has been added in [release 0.9.1](https://github.com/crowbarz/ha-pioneer_async/releases/tag/0.9.1)

**Comment by Tamas-Toth-ebola** [comment]
Thanks for it! Tried, works, happy :smile:
