### ISSUE TITLE
Pioneer AVR Unexpected exception: Zone 1 not found on AVR

### ISSUE THREAD

**Issue by lennie-BE** [crowbarz/ha-pioneer_async#58]
This integration stopped working some time ago after 2 years of perfect functionality.

Tried updating, but failed for a long time.

Now I was able to update but reinstalling the integration seems impossible.

I keep getting the error: 

> Pioneer AVR
> Unexpected exception: Zone 1 not found on AVR

Error log doesn't give much info:

> This error originated from a custom integration.
> 
> Logger: custom_components.pioneer_async.config_flow
> Source: custom_components/pioneer_async/config_flow.py:264
> integration: Pioneer AVR (documentation)
> First occurred: 7:52:41 PM (3 occurrences)
> Last logged: 10:57:14 PM
> 
> unexpected exception: Zone 1 not found on AVR

Would like to get this integration working again...

**Comment by crowbarz** [comment]
This sounds like your AVR has stopped responding on its API to the integration. Have you tried turning off the AVR at the wall outlet then powering it back on, waiting about a minute, then restarting the integration with the main zone off and with the main zone on?

Also, does the AVR still work with the iControlAV5 app on the phone? If not, then it is definitely a problem with your AVR.

In the next version, the Zone 1 not found error that causes integration setup to fail will become a warning and not prevent the integration from starting. However it will not be very useful if the AVR is not responding to requests via its API.

**Comment by lennie-BE** [comment]
Thank you very much! Powering the AVR down by pulling the plug and reconnecting a few minutes later did the trick!

**Comment by crowbarz** [comment]
Great to hear. That's amazing that your AVR lasted 2 years between full power cycles. Mine is power cycled daily via a smart plug to avoid it from getting into an unresponsive state.

**Comment by lennie-BE** [comment]
Good to know that whenever I have issues again this is the trick!
Thank you!
