### ISSUE TITLE
Repository to add in hacs

### ISSUE THREAD

**Issue by iewl** [crowbarz/ha-pioneer_async#6]
Hi,

I finally have HACS installed, but what repository should i add to get my VSX-933 working?

**Comment by iewl** [comment]
Thanks for you quick reply!
I was able to find the integration, but unfortunately the integration
cannot connect to the AVR.
I tried to add with:

media_player:
  - platform: pioneer
    host: 192.168.10.22
    port: 8102
    name: Pioneer

But this also was not a success.

If you have the time, could you explain what could be wrong? Or where I can
find help?

Thank you!

Op do 28 okt. 2021 om 18:27 schreef Crowbar Z ***@***.***>:

**Comment by crowbarz** [comment]
There are numerous possibilities of things that could go wrong. I'd suggest following [these instructions to enable debug logging](https://github.com/crowbarz/ha-pioneer_async#enabling-debugging), attempting to add the integration again and reviewing the Home Assistant log to figure out what is happening in your particular setup.

**Comment by iewl** [comment]
That gave me a lot more info!
I found this:
2021-11-05 12:40:15 DEBUG (MainThread)
[custom_components.pioneer_async.config_flow] >>
config.async_step_user({'name': 'Pioneer AVR', 'host': '192.168.10.22',
'port': 8102})
2021-11-05 12:40:15 DEBUG (MainThread)
[custom_components.pioneer_async.config_flow] >> validate_input({'name':
'Pioneer AVR', 'host': '192.168.10.22', 'port': 8102})
2021-11-05 12:40:15 INFO (MainThread) [aiopioneer.pioneer_avr] Starting
aiopioneer 0.1.7
2021-11-05 12:40:15 DEBUG (MainThread)
[custom_components.pioneer_async.config_flow] exception caught: [Errno 111]
Connect call failed ('192.168.10.22', 8102)

This is the same for port 23.
Where can I find the error numbers?



Op do 4 nov. 2021 om 22:41 schreef Crowbar Z ***@***.***>:

**Comment by crowbarz** [comment]
The messages show that a network connection to the AVR cannot be established by the integration. You should try manually establishing a connection to TCP port 8102 and 23 using `nc` or `telnet` from the server and/or within the Docker container that runs Home Assistant. The instant connection failed would suggest that the AVR (or possibly a firewall) is rejecting the connection. The integration won't work without being able to connect to your AVR.

If you can connect to the AVR via one of the Pioneer apps (eg. iControlAV5) then I'd suggest reviewing the app's settings and using those to connect, I believe the integration uses the same API as the app.
